[package]
name = "protolang-parser"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
itertools = "0.12.1"
once_cell = "1.19.0"
test-log = { version = "0.2.15", default-features = false, features = ["trace", "tracing-subscriber"] }
tracing = "0.1.40"
