on:
  push:
    tags:
      - '*'
name: Build and release
jobs:
  release:
    name: Release - ${{ matrix.platform.os_name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: protolang-generator
            name: protolang-linux-x86_64
            command: build

          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: protolang-generator.exe
            name: protolang-win-x86_64.exe
            command: both

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo output
        uses: Swatinem/rust-cache@v2

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: stable
          args: "--locked --release"
          strip: true

      - name: Prepare files to release
        run: |
          mv target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} ${{ matrix.platform.name }}

      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: protolang-${{ matrix.platform.os_name }}
          path: ${{ matrix.platform.name }}

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: ${{ matrix.platform.name }}
